### ISSUE TITLE
Initial characteristic read results in an unexpected call to onChange

### ISSUE THREAD

**Issue by Supereg** [StanfordSpezi/SpeziBluetooth#25]
### Description

Currently, we always read all characteristics of a service if they are defined in a BluetoothService. For `indicate` or `notify` characteristics the `onChange` handler would be called even for the initial characteristic read.
This is unintuitive. The `onChange` handler should only be called when the value was changed. For example a weight scale measurement characteristic should only call the onChance method if a new measurement is received. Calling onChange with the a value received upon connection is not intuitive and unexpected as it may represent a previous, outdated measurement.

### Reproduction

1. Connect to device
2. Observe `onChange` being called for subscribed characteristics

### Expected behavior

The `onChange` handler should only be called when an updated value is received (either through a notification or a manual read) not when we receive the initial value upon connection establishment.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
Nice; thank you @Supereg!
