### ISSUE TITLE
Crash Within `onChange` Observation of Characteristics

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordSpezi/SpeziBluetooth#26]
### Description

We have multiple characteristics within a single service that are following a similar pattern of having one or more characteristics that are notifying and observed using `onChange`:

```swift
final class ExampleService: BluetoothService, MeasurementService, @unchecked Sendable {
    static let id: CBUUID = // ...

    @Characteristic(id: /* ... */, notify: true)
    private var exampleCharacteristic: ExampleCharacteristic?
    

    init() {
        $exampleCharacteristic.onChange { exampleCharacteristic in
            // ...
        }
    }
}
```

Unfortunately we sometimes seem to run into a crash that causes the application to crash with a following stack trace:
- 0 `in swift_isUniquelyReferenced_nonNull_native ()`
- 1 `in specialized Dictionary._Variant.isUniquelyReferenced() ()`
- 2 `in specialized Dictionary._Variant.setValue(_:forKey:) ()`
- 3 `in specialized Dictionary.subscript.setter ()`
- 4 [`in ClosureRegistrar.insert<A>(for:closure:)`](https://github.com/StanfordSpezi/SpeziBluetooth/blob/main/Sources/SpeziBluetooth/Model/PropertySupport/ClosureRegistrar.swift#L29)
- 5 [in CharacteristicAccessor<A>.onChange(perform:)](https://github.com/StanfordSpezi/SpeziBluetooth/blob/main/Sources/SpeziBluetooth/Model/PropertySupport/CharacteristicAccessor.swift#L117)
- 6 `onChange` call in the above code example

### Reproduction

We can not reproduce this on every run of the app, leading us to believe this is a race condition happening during the initialization of the service within our Bluetooth device implementation. 

### Expected behavior

According to the error this type of crash happens when an instance is not fully initialized but accessed before. The `registrations` type should be initialized using the default assigned values. Maybe doing this explicitly in the init call could resolve this?

If it would be a race condition, I would think that a simple sync lock around the access to the dictionary might resolve this issue without too much harm as on change registry should not be something that is happening too frequently and we would generally not expect too many concurrent accesses to the property?

### Additional context

Happy to get any input, e.g., from @Supereg if you have seen this before and/or if any of the ideas above might be applicable.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
Actually could only find this in the one app at the one part of the code.

I have modified the code like this and it seems to mitigate the crashes for now which might be a way to point to the solution (contains some more context but I think this should not be relevant for the issue):
```swift
final class ExampleService: BluetoothService, MeasurementService, @unchecked Sendable {
    static let id: CBUUID = // ...

    @Characteristic(id: /* ... */, notify: true)
    private var exampleCharacteristic: ExampleCharacteristic?

    @CustomActor
    var output: [Int] = []
    

    init() {
        Task { @CustomActor in
            output.reserveCapacity(15_000)
        
            $exampleCharacteristic.onChange { exampleCharacteristic in
                // Move off the bluetooth queue as fast as possible!
                Task { @CustomActor in
                    self.output.append(contentsOf: exampleCharacteristic.output)
                }
            }
        }
    }
}
```

**Comment by Supereg** [comment]
Thanks for providing the workaround. I'll try to eventually reproduce the issue. Happy to discuss it in more detail in the next meeting as well 👍

**Comment by Supereg** [comment]
Do you still observe the behavior if you remove the `output` variable in the example (or deliberately initialize it beforehand)? I could imagine that the problem is, that we reference self in the closure while it isn't fully initialized (as the output variable is bound and initialized on a different actor). However, I had a similar pattern in a different project as well If I remember correctly.
Another try would be seeing if it still crashes if you just pass an empty closure for now. This could indicate if the issue is indeed the capture to `self`.

**Comment by PSchmiedmayer** [comment]
This crash has no longer occurred with the current setup and with the latest SpeziBluetooth 2.X and 3.X changes using the initializers to setup onChange notifications is no longer supported. Closing this issue accordingly.
