### ISSUE TITLE
Device Pairing UI and Functionality

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordSpezi/SpeziBluetooth#4]
### Problem

The current implementation automatically connects with any devices offering the provided services.

### Solution

The Spezi Bluetooth Swift Package should include an additional target that allows developers to display a standardized UI to discover, select, and monitor the status of connected devices. It should provide some customization possibilities, e.g., using a way to customize the view representing a single device.

The main Spezi Bluetooth module should include additional APIs to develop such a UI and pair with a specified device.

### Additional context

The UI developed in the NAMS application: https://github.com/StanfordBDHG/NAMS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by Supereg** [comment]
This will be resolved with https://github.com/StanfordSpezi/SpeziDevices/pull/1
